name: med-ml
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - jupyterlab
  - pyyaml
  - scikit-learn
  - torchvision
  - pytorch
  - cpuonly
  - torchaudio
  - tqdm
  - matplotlib
  - lightgbm